// Surface grammar evaluation tables: npx tsx scripts/surface/analyze.ts > docs/surface/tables.md
// Per page: performance (parts, generation time), RNG draws, repetition (City / Street) for kit-v4
// and the current kit; then the anatomy census and the page signals the surface spent.
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { building, type Program } from "../../src/lib/pixelcity/kit/buildings";
import { Kit } from "../../src/lib/pixelcity/kit/core";
import { generateKitDistrict, newTrace, type KitTrace } from "../../src/lib/pixelcity/kit/district";
import { generateSurfaceLab, type LabKit } from "../../src/lib/pixelcity/kit/lab";
import { realPage } from "../../src/lib/pixelcity/kit/real-page";
import type { Anatomy } from "../../src/lib/pixelcity/kit/surface";
import { building as buildingV4 } from "../../src/lib/pixelcity/kit-v4/buildings";
import { Kit as KitV4 } from "../../src/lib/pixelcity/kit-v4/core";
import { generateKitDistrict as v4, newTrace as newTraceV4, type KitTrace as KitTraceV4 } from "../../src/lib/pixelcity/kit-v4/district";
import { realPage as realPageV4 } from "../../src/lib/pixelcity/kit-v4/real-page";
import type { ArchStyle } from "../../src/lib/pixelcity/grammar";
import type { Part } from "../../src/lib/pixelcity/types";
import { vacantFingerprint } from "../../src/lib/pixelcity/vacant-fingerprint";
import { DATASET } from "../real-pages/dataset";

const snap = (id: string) => JSON.parse(readFileSync(`docs/real-pages/snapshots/${id}.json`, "utf8"));
const sha = (s: string) => createHash("sha1").update(s).digest("hex").slice(0, 12);
const pct = (a: number, b: number) => `${b ? Math.round((100 * a) / b) : 0}%`;

// RNG draws: count every kit.rand (kit.pick goes through it).
let draws = 0;
for (const K of [Kit, KitV4] as Array<{ prototype: { rand: (a: number, b?: number) => number } }>) {
  const r = K.prototype.rand;
  K.prototype.rand = function (this: unknown, a: number, b?: number) {
    draws++;
    return r.call(this, a, b);
  };
}

/** Geometry of one building in its own frame (front = +z of its main volume); colour ignored. */
function signature(parts: Part[], r: [number, number]) {
  const ps = parts.slice(r[0], r[1]).filter((q) => q.mesh !== "sprite" && q.mesh !== "sign");
  const main = ps.reduce((m, q) => (q.w * q.d * q.h > m.w * m.d * m.h ? q : m), ps[0]);
  if (!main) return "empty";
  const c = Math.cos(-main.rotY);
  const s = Math.sin(-main.rotY);
  const f = (v: number) => (Math.abs(v) < 0.005 ? 0 : v).toFixed(2);
  return sha(
    ps
      .map((q) => {
        const dx = q.x - main.x;
        const dz = q.z - main.z;
        return `${q.mesh}|${q.surf}|${q.variant ?? 0}|${f(dx * c + dz * s)}|${f(-dx * s + dz * c)}|${f(q.y)}|${f(q.w)}|${f(q.h)}|${f(q.d)}`;
      })
      .sort()
      .join(";"),
  );
}
type B = { block: [number, number]; parts: [number, number] };
function repetition(parts: Part[], bs: B[]) {
  const sig = bs.map((b) => signature(parts, b.parts));
  let adj = 0;
  let pairs = 0;
  for (let i = 1; i < bs.length; i++)
    if (bs[i].block[0] === bs[i - 1].block[0] && bs[i].block[1] === bs[i - 1].block[1]) {
      pairs++;
      if (sig[i] === sig[i - 1]) adj++;
    }
  const counts = new Map<string, number>();
  for (const s of sig) counts.set(s, (counts.get(s) ?? 0) + 1);
  return { distinct: counts.size, n: bs.length, adj, pairs, maxCopies: Math.max(...counts.values()) };
}
const median = (xs: number[]) => xs.sort((a, b) => a - b)[Math.floor(xs.length / 2)];

console.log("# Surface grammar — evaluation tables\n");
console.log("Generated by `npx tsx scripts/surface/analyze.ts`. kit-v4 = before (semantic hygiene), current = surface grammar. Seed 7, day.\n");

console.log("## 1. Performance, RNG and repetition per page\n");
console.log("| page | parts v4 → now | gen ms v4 → now | RNG draws v4 → now | distinct buildings v4 → now | identical neighbours v4 → now | most copies v4 → now |");
console.log("|---|---|---|---|---|---|---|");
const census: Anatomy[] = [];
const signalsByPage: Array<[string, string[]]> = [];
const totals = { p4: 0, p5: 0, t4: 0, t5: 0, d4: 0, d5: 0 };
for (const e of DATASET) {
  const s = snap(e.id);
  const p = realPage(s);
  const q = realPageV4(s);
  const t4: number[] = [];
  const t5: number[] = [];
  let a: ReturnType<typeof generateKitDistrict> | undefined;
  let b: ReturnType<typeof v4> | undefined;
  const ta: KitTrace = newTrace();
  const tb: KitTraceV4 = newTraceV4();
  let d4 = 0;
  let d5 = 0;
  for (let k = 0; k < 5; k++) {
    let t0 = performance.now();
    draws = 0;
    b = v4(q.fp, { profile: q.plan, time: "day", seed: 7, trace: k === 0 ? tb : undefined });
    t4.push(performance.now() - t0);
    d4 = draws;
    t0 = performance.now();
    draws = 0;
    a = generateKitDistrict(p.fp, { profile: p.plan, time: "day", seed: 7, trace: k === 0 ? ta : undefined });
    t5.push(performance.now() - t0);
    d5 = draws;
  }
  const r4 = repetition(b!.parts, tb.buildings);
  const r5 = repetition(a!.parts, ta.buildings);
  totals.p4 += b!.parts.length;
  totals.p5 += a!.parts.length;
  totals.t4 += median(t4);
  totals.t5 += median(t5);
  totals.d4 += d4;
  totals.d5 += d5;
  console.log(
    `| ${e.id} | ${b!.parts.length} → ${a!.parts.length} | ${median(t4).toFixed(1)} → ${median(t5).toFixed(1)} | ${d4} → ${d5} | ${r4.distinct}/${r4.n} → ${r5.distinct}/${r5.n} | ${r4.adj}/${r4.pairs} → ${r5.adj}/${r5.pairs} | ${r4.maxCopies} → ${r5.maxCopies} |`,
  );
  for (const bd of ta.buildings) census.push(...bd.anatomy);
  signalsByPage.push([e.id, [...new Set(ta.buildings.flatMap((bd) => bd.anatomy.flatMap((A) => A.signals.map((x) => x.split(" → ")[1] ? `${x.split(" ")[0]} → ${x.split(" → ")[1]}` : x))))]]);
}
console.log(`| **all** | ${totals.p4} → ${totals.p5} (${((100 * (totals.p5 - totals.p4)) / totals.p4).toFixed(1)}%) | ${totals.t4.toFixed(0)} → ${totals.t5.toFixed(0)} | ${totals.d4} → ${totals.d5} | | | |`);
console.log("\nStreet surfaces, furniture and traffic are the same code in both kits; RNG differences come from buildings.");
console.log("Distinct buildings: geometry signatures in each building's own frame (mesh, surface, variant, local position, size; colour ignored).");
console.log("Identical neighbours: consecutive buildings of the same block with the same signature.\n");

console.log("## 2. RNG draws per building (Surface Grammar Lab, same programs)\n");
console.log("| set · style | draws per building v4 → now |");
console.log("|---|---|");
const kits: Record<string, LabKit> = {
  v4: { Kit: KitV4 as unknown as LabKit["Kit"], building: buildingV4 as unknown as LabKit["building"] },
  now: { Kit: Kit as unknown as LabKit["Kit"], building: building as unknown as (kit: never, w: number, d: number, P: Program) => number },
};
for (const set of ["programs", "corners", "roofs", "sizes"] as const)
  for (const style of ["classic", "retro", "modern"] as ArchStyle[]) {
    const row: string[] = [];
    for (const v of ["v4", "now"]) {
      draws = 0;
      const lab = generateSurfaceLab(kits[v], vacantFingerprint(), { set, style });
      row.push((draws / lab.cells.length).toFixed(1));
    }
    console.log(`| ${set} · ${style} | ${row[0]} → ${row[1]} |`);
  }

console.log("\n## 3. Anatomy census (current kit, all pages)\n");
const tally = (f: (A: Anatomy) => string) => {
  const m = new Map<string, number>();
  for (const A of census) m.set(f(A), (m.get(f(A)) ?? 0) + 1);
  return [...m.entries()].sort((x, y) => y[1] - x[1]).map(([k, n]) => `${k} ${pct(n, census.length)}`).join(" · ");
};
console.log(`${census.length} volumes.\n`);
console.log(`- **use**: ${tally((A) => A.use)}`);
console.log(`- **ground**: ${tally((A) => A.ground.kind)}`);
console.log(`- **base**: ${tally((A) => (A.base.floors ? `${A.base.floors}f ${A.base.treatment}` : "none"))}`);
console.log(`- **body**: ${tally((A) => `${A.body.surf}/${A.body.pattern}`)}`);
console.log(`- **crown**: ${tally((A) => A.crown.kind)}`);
console.log(`- **roof service**: ${tally((A) => A.roof.service)}`);
console.log(`- **roof occupied**: ${tally((A) => A.roof.occupied)}`);
console.log(`- **corner**: ${tally((A) => (A.corner.condition ? A.corner.treatment : "mid-block"))}`);
const det = new Map<string, number>();
for (const A of census) for (const d of A.details) det.set(d.split(":")[0], (det.get(d.split(":")[0]) ?? 0) + 1);
console.log(`- **detail families**: ${[...det.entries()].sort((x, y) => y[1] - x[1]).map(([k, n]) => `${k} ${n}`).join(" · ")}`);

console.log("\n## 4. Page signals spent at the surface\n");
console.log("| page | regularity | headings | interactivity | linkDensity | surface effects |");
console.log("|---|---|---|---|---|---|");
for (const [id, sigs] of signalsByPage) {
  const fp = realPage(snap(id)).fp;
  console.log(`| ${id} | ${fp.regularity.toFixed(2)} | ${fp.headings.toFixed(2)} | ${fp.interactivity.toFixed(2)} | ${fp.linkDensity.toFixed(2)} | ${sigs.map((x) => x.replace(/^(\w+) [\d.]+/, "$1")).filter((x, i, a) => a.indexOf(x) === i).join("; ") || "—"} |`);
}
