"""Markdown tables from docs/e2e/metrics.json and docs/e2e/visual.json: python3 scripts/e2e/tables.py > docs/e2e/tables.md"""
import json, statistics as st
m = json.load(open("docs/e2e/metrics.json")); ids = m["ids"]; L = m["layers"]
vis = json.load(open("docs/e2e/visual.json")) if __import__("os").path.exists("docs/e2e/visual.json") else None
AB = {"reference": "wiki", "reference-2": "wik2", "docs": "pydo", "shop": "ikea", "saas": "linr", "saas-2": "verc", "institution": "gouk", "media": "nasa", "oldweb": "pgrm", "portfolio": "port", "app": "ghub", "news": "guar", "forum": "lobs", "directory": "crgs"}
ORDER = ["shop", "docs", "reference", "reference-2", "saas", "saas-2", "institution", "media", "oldweb", "portfolio", "app", "news", "forum", "directory"]
def mat(M, order, idx):
    out = ["| | " + " | ".join(AB[p] for p in order) + " |", "|---" * (len(order) + 1) + "|"]
    for a in order:
        out.append(f"| **{AB[a]}** | " + " | ".join("—" if a == b else f"{M[idx.index(a)][idx.index(b)]:.2f}" for b in order) + " |")
    return "\n".join(out)
print("# End-to-end differentiation — tables\n")
print("Generated by `scripts/e2e/tables.py` from `metrics.json` / `visual.json`. Abbreviations: " + ", ".join(f"{v} = {k}" for k, v in AB.items()) + ".\n")
print("## 1. Layer summary (metric fingerprints, day, seed 7)\n")
print("| layer | page↔page mean | min | seed noise mean (max) | style noise mean | page / seed | page / style | pairs ≤ seed max | page↔page, all in one style | ρ with semantics |")
print("|---|---|---|---|---|---|---|---|---|---|")
for l in L:
    s = m["summary"][l]
    ps = "∞ (seed has no effect)" if s["seedMean"] < 1e-9 else f"{s['pageOverSeed']:.1f}"
    pst = "∞ (style has no effect)" if s["styleMean"] < 1e-9 else f"{s['pageOverStyle']:.1f}"
    print(f"| {l} | {s['pageMean']:.3f} | {s['pageMin']:.3f} | {s['seedMean']:.3f} ({s['seedMax']:.3f}) | {s['styleMean']:.3f} | {ps} | {pst} | {s['pairsBelowSeedMax']}/91 | {s['sameStyleMean']:.3f} | {s['rhoSemantics']:.2f} |")
print("\nRank agreement between consecutive layers (Spearman over the 91 page pairs):\n")
print(" ".join(f"{c['from']} —{c['rho']:.2f}→" for c in m["consecutive"]) + f" {m['consecutive'][-1]['to']}\n")
if vis:
    print("## 2. Final pixels (screenshots, same camera)\n")
    print("| view | page↔page mean | same page, seed 8 | same page → classic (10 pages not classic) | same page → modern (8 pages not modern) | page / seed | page / style | page↔page with style fixed (classic) | kit-v5 page↔page | kit-v4 page↔page |")
    print("|---|---|---|---|---|---|---|---|---|---|")
    for v, e in vis["views"].items():
        sd = e.get("seed8SamePage", {}).get("mean"); cl = e.get("classicSamePage", {}).get("mean"); mo = e.get("modernSamePage", {}).get("mean")
        f = lambda x: f"{x:.2f}" if x is not None else "–"
        # Style noise only over pages not already in the forced style (else forcing changes nothing).
        so = m["styleOf"]
        exc = [d for k in ("classic", "modern") if f"{k}SamePage" in e for p, d in e[f"{k}SamePage"]["per"].items() if so[p] != k]
        sty = st.mean(exc) if exc else None
        cl = st.mean([d for p, d in e["classicSamePage"]["per"].items() if so[p] != "classic"]) if "classicSamePage" in e else None
        mo = st.mean([d for p, d in e["modernSamePage"]["per"].items() if so[p] != "modern"]) if "modernSamePage" in e else None
        print(f"| {v} | {e['pageMean']:.2f} | {f(sd)} | {f(cl)} | {f(mo)} | {f(e['pageMean'] / sd) if sd else '–'} | {f(e['pageMean'] / sty) if sty else '–'} | {f(e.get('classicPageMean'))} | {f(e.get('v5PageMean'))} | {f(e.get('v4PageMean'))} |")
    print()
print("## 3. Distance matrices\n")
for l in L:
    print(f"### {l}\n"); print(mat(m["matrix"][l], ORDER, ids)); print()
if vis:
    for v, e in vis["views"].items():
        print(f"### pixels · {v}\n"); print(mat(e["matrix"], [p for p in ORDER if p in e["ids"]], e["ids"])); print()
print("## 4. Nearest neighbour per page\n")
cols = L + ([f"px {v}" for v in vis["views"]] if vis else [])
print("| page | " + " | ".join(cols) + " |"); print("|---" * (len(cols) + 1) + "|")
for p in ORDER:
    row = []
    for l in L:
        M = m["matrix"][l]; i = ids.index(p); j = min((x for x in range(len(ids)) if x != i), key=lambda x: M[i][x]); row.append(f"{AB[ids[j]]} {M[i][j]:.2f}")
    if vis:
        for v, e in vis["views"].items():
            if p not in e["ids"]: row.append("–"); continue
            M = e["matrix"]; i = e["ids"].index(p); j = min((x for x in range(len(e["ids"])) if x != i), key=lambda x: M[i][x]); row.append(f"{AB[e['ids'][j]]} {M[i][j]:.2f}")
    print(f"| **{AB[p]}** | " + " | ".join(row) + " |")
print("\n## 5. Signal survival (Spearman ρ across the 14 pages between the page signal and each downstream effect)\n")
print("| signal | stage | effect | ρ |"); print("|---|---|---|---|")
for s in m["signals"]:
    for k, stg in enumerate(s["stages"]):
        print(f"| {s['name'] if k == 0 else ''} | {stg['layer']} | {stg['what']} | {stg['rho']:.2f} |")
