"""BEFORE (kit-v6, docs/e2e) × AFTER (docs/composition) tables: python3 scripts/composition/compare.py > docs/composition/tables.md"""
import json, statistics as st, sys, os
sys.path.insert(0, "scripts/e2e")
import numpy as np
from visual_lib import features, comps
mb = json.load(open("docs/e2e/metrics.json")); ma = json.load(open("docs/composition/metrics-after.json"))
vb = json.load(open("docs/e2e/visual.json")); va = json.load(open("docs/composition/visual-after.json"))
ids = mb["ids"]; L = mb["layers"]
def rank(xs):
    o = sorted(range(len(xs)), key=lambda i: xs[i]); r = [0] * len(xs)
    for k, i in enumerate(o): r[i] = k
    return r
def rho(a, b):
    ra, rb = rank(a), rank(b); x, y = st.mean(ra), st.mean(rb)
    n = sum((p - x) * (q - y) for p, q in zip(ra, rb)); d = (sum((p - x) ** 2 for p in ra) * sum((q - y) ** 2 for q in rb)) ** 0.5
    return n / d
pairs = [(a, b) for i, a in enumerate(ids) for b in ids[i + 1:]]
def md(m, l, a, b): return m["matrix"][l][ids.index(a)][ids.index(b)]
def vd(v, view, a, b):
    e = v["views"][view]; vi = e["ids"]; return e["matrix"][vi.index(a)][vi.index(b)]
def pct(vals, x): return 100 * sum(1 for y in vals if y < x) / len(vals)
print("# Intra-territory composition — BEFORE (kit-v6) × AFTER\n")
print("Generated by `scripts/composition/compare.py`. BEFORE = the end-to-end validation (`docs/e2e`), AFTER = this pass; same snapshots, seed 7, cameras. Percentiles are over the 91 page pairs of the same layer/view.\n")
print("## 1. craigslist × Paul Graham\n")
print("| layer / view | BEFORE | AFTER |")
print("|---|---|---|")
for l in L:
    vb_ = [md(mb, l, a, b) for a, b in pairs]; va_ = [md(ma, l, a, b) for a, b in pairs]
    b, a = md(mb, l, "directory", "oldweb"), md(ma, l, "directory", "oldweb")
    print(f"| {l} (metric) | {b:.3f} (p{pct(vb_, b):.0f}) | {a:.3f} (p{pct(va_, a):.0f}) |")
for view in ("flat", "city"):
    vb_ = [vd(vb, view, a, b) for a, b in pairs]; va_ = [vd(va, view, a, b) for a, b in pairs]
    b, a = vd(vb, view, "directory", "oldweb"), vd(va, view, "directory", "oldweb")
    print(f"| **pixels {view}** | {b:.2f} (p{pct(vb_, b):.0f}) | **{a:.2f} (p{pct(va_, a):.0f})** |")
print("\n## 2. Corpus\n")
print("| measure | BEFORE | AFTER |")
print("|---|---|---|")
sem = [md(mb, "semantics", a, b) for a, b in pairs]
for l in ("composition", "massing"):
    print(f"| ρ semantics ↔ {l} (metric) | {rho(sem, [md(mb, l, a, b) for a, b in pairs]):.2f} | {rho(sem, [md(ma, l, a, b) for a, b in pairs]):.2f} |")
for view in ("flat", "city"):
    print(f"| ρ semantics ↔ pixels {view} | {rho(sem, [vd(vb, view, a, b) for a, b in pairs]):.2f} | {rho(sem, [vd(va, view, a, b) for a, b in pairs]):.2f} |")
    print(f"| mean page↔page pixels {view} | {st.mean([vd(vb, view, a, b) for a, b in pairs]):.2f} | {st.mean([vd(va, view, a, b) for a, b in pairs]):.2f} |")
# Seed noise (city): craigslist re-measured with the new kit; the other 13 cities are byte-identical.
med = np.array(va["views"]["city"]["componentMedians"])
d8 = float((comps(features("docs/screenshots/composition/after/directory-city.png"), features("docs/screenshots/composition/after/directory-city-seed8.png")) / med).mean())
seedB = vb["views"]["city"]["seed8SamePage"]["per"]; seedA = dict(seedB); seedA["directory"] = d8
pb = st.mean([vd(vb, "city", a, b) for a, b in pairs]) / st.mean(seedB.values()); pa = st.mean([vd(va, "city", a, b) for a, b in pairs]) / st.mean(seedA.values())
print(f"| page ÷ seed noise, pixels city | {pb:.2f} | {pa:.2f} (craigslist seed noise {seedB['directory']:.2f} → {d8:.2f}) |")
print("\n## 3. Retention: internal structure → flat\n")
idx = json.load(open("docs/composition/structure-index.json"))
print("Internal-structure index (Σ parcelled lots × log₂ groups / 256): " + ", ".join(f"{k} {v:.2f}" for k, v in idx.items() if v) + "; every other page 0 (its parcelled land, if any, is one sequence or has no structure).\n")
others = [p for p in ids if p != "directory"]
for view in ("flat", "city"):
    b = [vd(vb, view, "directory", p) for p in others]; a = [vd(va, view, "directory", p) for p in others]
    print(f"- craigslist → the other 13 pages, pixels {view}: mean {st.mean(b):.2f} → {st.mean(a):.2f}; nearest {min(b):.2f} ({others[b.index(min(b))]}) → {min(a):.2f} ({others[a.index(min(a))]})")
print("\nOnly craigslist carries internal structure on parcelled land in this corpus, so a corpus-wide ρ between structure and flat is degenerate; the synthetic sweep (test:composition) measures the response curve instead.")
