// Openings depth tables: npx tsx scripts/openings/analyze.ts > docs/openings/tables.md
import { readFileSync } from "node:fs";
import { generateKitDistrict, newTrace } from "../../src/lib/pixelcity/kit/district";
import { decodeOpening } from "../../src/lib/pixelcity/kit/openings";
import { realPage } from "../../src/lib/pixelcity/kit/real-page";
import { generateKitDistrict as v5 } from "../../src/lib/pixelcity/kit-v5/district";
import { realPage as realPageV5 } from "../../src/lib/pixelcity/kit-v5/real-page";
import { Surf } from "../../src/lib/pixelcity/types";
import { DATASET } from "../real-pages/dataset";

const snap = (id: string) => JSON.parse(readFileSync(`docs/real-pages/snapshots/${id}.json`, "utf8"));
const median = (xs: number[]) => xs.sort((a, b) => a - b)[Math.floor(xs.length / 2)];
console.log("# Openings depth — tables\n");
console.log("Generated by `npx tsx scripts/openings/analyze.ts`. kit-v5 = before (surface grammar), now = openings depth. Seed 7, day.\n");
console.log("## 1. Parts, generation time and treated openings per page\n");
console.log("| page | parts v5 → now | gen ms v5 → now (median of 7) | windowed parts | with depth | punched / ribbon / shop glazing |");
console.log("|---|---|---|---|---|---|");
const tally = new Map<string, number>();
let t5s = 0;
let t6s = 0;
for (const e of DATASET) {
  const s = snap(e.id);
  const p5 = realPageV5(s);
  const p6 = realPage(s);
  const a: number[] = [];
  const b: number[] = [];
  let c5 = v5(p5.fp, { profile: p5.plan, time: "day", seed: 7 });
  let c6 = generateKitDistrict(p6.fp, { profile: p6.plan, time: "day", seed: 7 });
  for (let k = 0; k < 7; k++) {
    let t = performance.now();
    c5 = v5(p5.fp, { profile: p5.plan, time: "day", seed: 7 });
    a.push(performance.now() - t);
    t = performance.now();
    c6 = generateKitDistrict(p6.fp, { profile: p6.plan, time: "day", seed: 7 });
    b.push(performance.now() - t);
  }
  t5s += median(a);
  t6s += median(b);
  let windowed = 0;
  let deep = 0;
  const kinds = { 14: 0, 15: 0, 13: 0 } as Record<number, number>;
  for (const q of c6.parts) {
    if (q.surf !== Surf.FRAMED && q.surf !== Surf.BANDS && q.surf !== Surf.STORE && q.surf !== Surf.GLASS) continue;
    windowed++;
    if (decodeOpening(q.variant ?? 0).on) {
      deep++;
      kinds[q.surf]++;
    }
  }
  console.log(`| ${e.id} | ${c5.parts.length} → ${c6.parts.length} | ${median(a).toFixed(1)} → ${median(b).toFixed(1)} | ${windowed} | ${deep} (${Math.round((100 * deep) / windowed)}%) | ${kinds[14]} / ${kinds[15]} / ${kinds[13]} |`);
  const t = newTrace();
  generateKitDistrict(p6.fp, { profile: p6.plan, time: "day", seed: 7, trace: t });
  for (const bd of t.buildings) for (const A of bd.anatomy) {
    const k = `${A.opening.glazing} · ${A.opening.depth} · ${A.opening.frame}${A.opening.sill ? " + sill" : ""} · ${A.opening.sash} sash`;
    tally.set(k, (tally.get(k) ?? 0) + 1);
  }
}
console.log(`| **all** | | ${t5s.toFixed(0)} → ${t6s.toFixed(0)} | | | |`);
console.log("\nWindowed parts: FRAMED, BANDS, STORE and GLASS (curtain walls stay flush by design). The parts are the same objects as kit-v5; only their variant bits change.\n");
console.log("## 2. Opening treatments (volumes, 14 pages)\n");
console.log("| treatment | volumes |");
console.log("|---|---|");
for (const [k, n] of [...tally.entries()].sort((x, y) => y[1] - x[1])) console.log(`| ${k} | ${n} |`);
